name: Running yolo containers
hosts: all
tasks:
vars:
  client_image: dmuchoki/client-image:2.0.0
  backend_image: dmuchoki/backend-image:1.0.0
- name: Pull client image
      community.docker.docker-image:
      name: {{ client_image }}
      source: pull
- name: Pull backend image
      community.docker.docker-image:
      name: {{ backend_image }}
      source: pull
- name: create folder
       ansible.builtin.file:
       path: /opt/yolo
       state: directory
- name: Copying docker-compose file 
      ansible.builtin.template:
      src: ../docker-compose.yaml
      dest: "/opt/yolo/docker-compose.yaml"